[colors.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[colors.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x787c99"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xa9b1d6"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "JetBrains Mono NF"

[font.bold_italic]
family = "JetBrains Mono NF"

[font.italic]
family = "JetBrains Mono NF"

[font.normal]
family = "JetBrains Mono NF"

[schemes.tokyo-night.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[schemes.tokyo-night.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x787c99"
yellow = "0xe0af68"

[schemes.tokyo-night.primary]
background = "0x1a1b26"
foreground = "0xa9b1d6"

[schemes.tokyo-night-storm.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[schemes.tokyo-night-storm.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x9699a8"
yellow = "0xe0af68"

[schemes.tokyo-night-storm.primary]
background = "0x24283b"
foreground = "0xa9b1d6"
